### ISSUE TITLE
Application doesn't load

### ISSUE THREAD

**Issue by olka** [knoldus/activator-play-slick-app#5]
After execution of ./activator run Netty starts on :9000 but index page loading endlessly
In console following stacktrace can be found:
```
PlayRequestHandler - Exception caught in Netty
[info] java.security.PrivilegedActionException: null
[info] 	at java.security.AccessController.doPrivileged(Native Method)
[info] 	at play.runsupport.Reloader$.play$runsupport$Reloader$$withReloaderContextClassLoader(Reloader.scala:40)
[info] 	at play.runsupport.Reloader.reload(Reloader.scala:337)
[info] 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:118)
[info] 	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:116)
[info] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[info] 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[info] 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[info] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info] Caused by: java.util.concurrent.TimeoutException: Futures timed out after [300000 milliseconds]
[info] 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[info] 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[info] 	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[info] 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info] 	at scala.concurrent.Await$.result(package.scala:190)
[info] 	at play.forkrun.ForkRun$$anonfun$askForReload$1.apply(ForkRun.scala:128)
[info] 	at play.forkrun.ForkRun$$anonfun$askForReload$1.apply(ForkRun.scala:126)
[info] 	at play.runsupport.Reloader$$anonfun$reload$1.apply(Reloader.scala:339)
[info] 	at play.runsupport.Reloader$$anon$3.run(Reloader.scala:44)
[info] 	at java.security.AccessController.doPrivileged(Native Method)
```

**Comment by satendrakumar06** [comment]
@olka  Which OS are you using & what is you JDK version ?

**Comment by olka** [comment]
@satendrakumar06  it appeared that this is an issue with activator: https://github.com/typesafehub/activator/issues/1117

**Comment by iurisman** [comment]
I workaround a fix?

**Comment by mrsushil118** [comment]
@iurisman, It will work with above mentioned solution.
